### ISSUE TITLE
Apparently installing latest build of Caitlyn in VS2010 breaks the IDE

### ISSUE THREAD

**Issue by jsbattig** [GeertvanHorrik/Caitlyn#3] opened 2014-05-22 00:10 UTC
This is how my IDE looks like "normally":

![image](https://cloud.githubusercontent.com/assets/1790597/3048304/e943c548-e144-11e3-9908-b9c71cc715a5.png)

this is how it looks like _after_ installing and enabling Caitlyn:

![image](https://cloud.githubusercontent.com/assets/1790597/3048312/185fbfe4-e145-11e3-85e3-e9a336e48281.png)

apparently it disables visual studio ability to show anything.
This is the oddest one, look at the "Extension Manager" dialog:

![image](https://cloud.githubusercontent.com/assets/1790597/3048315/31b93bdc-e145-11e3-8219-a8de37d948fd.png)

Not sure where to go from here. So far, this extension seems to be the most refined one to link source files.
The other available extension "Project Linker" doesn't synchronize with an already existing project.

**Comment by GeertvanHorrik** [comment] 2014-05-23 07:33
That is really weird. When you uninstall, this is gone? I don't have vs2010 anymore so I cannot reproduce this issue for you. I am also moving to shared projects (which is available since VS 2013 update 2) which works better (1 project containing all shared files).

**Closed as completed** 2019-10-25 12:10 UTC
